kind: DeploymentConfig
apiVersion: v1
metadata:
  name: iot-sigfox-adapter
  labels:
    app: iot-sigfox-adapter
    deploymentconfig: iot-sigfox-adapter
    enmasse-component: iot
spec:
  replicas: 1

  selector:
    app: iot-sigfox-adapter
    deploymentconfig: iot-sigfox-adapter

  strategy:
    type: Rolling

  triggers:

    - type: ConfigChange

    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - sigfox-adapter
        from:
          kind: ImageStreamTag
          name: iot-sigfox-adapter:latest

  template:
    metadata:
      labels:
        app: iot-sigfox-adapter
        deploymentconfig: iot-sigfox-adapter
    spec:
      containers:

# Main protocol adapter container

      - name: sigfox-adapter
        imagePullPolicy: Always
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/config/
        - name: SPRING_PROFILES_ACTIVE
          value: prometheus
        - name: LOGGING_CONFIG
          value: file:///etc/config/logback-spring.xml
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HONO_AUTH_HOST
          value: iot-auth-service.$(KUBERNETES_NAMESPACE).svc
        - name: HONO_MESSAGING_HOST
          value: localhost
        - name: HONO_MESSAGING_PORT
          value: "5672"
        - name: HONO_COMMAND_HOST
          value: localhost
        - name: HONO_COMMAND_PORT
          value: "5672"

        - name: HONO_CREDENTIALS_HOST
          value: iot-device-registry.$(KUBERNETES_NAMESPACE).svc
        - name: HONO_DEVICE_CONNECTION_HOST
          value: iot-device-registry.$(KUBERNETES_NAMESPACE).svc
        - name: HONO_REGISTRATION_HOST
          value: iot-device-registry.$(KUBERNETES_NAMESPACE).svc
        - name: HONO_TENANT_HOST
          value: iot-tenant-service.$(KUBERNETES_NAMESPACE).svc

        - name: HONO_CREDENTIALS_TRUST_STORE_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        - name: HONO_DEVICE_CONNECTION_TRUST_STORE_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        - name: HONO_REGISTRATION_TRUST_STORE_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        - name: HONO_TENANT_TRUST_STORE_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

        - name: HONO_CREDENTIALS_USERNAME
          value: http-adapter@HONO
        - name: HONO_DEVICE_CONNECTION_USERNAME
          value: http-adapter@HONO
        - name: HONO_REGISTRATION_USERNAME
          value: http-adapter@HONO
        - name: HONO_TENANT_USERNAME
          value: http-adapter@HONO

        readinessProbe:
          httpGet:
            path: /readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 180
        resources:
          limits:
            memory: 512Mi
        ports:
        - containerPort: 8778
          name: jolokia
        - containerPort: 8443
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /etc/tls
          name: tls
          readOnly: true

# Qpid dispatch router configurator

      - name: qdr-cfg
        image: 'enmasseproject/iot-proxy-configurator:latest'
        volumeMounts:
        - mountPath: /var/qdr-certs
          name: qdr-tmp-certs
        resources:
          limits:
            memory: 64Mi

# Proxy Qpid dispatch router

      - name: qdr-proxy
        image: 'enmasseproject/qdrouterd-base:1.6.0-rc1'
        args: ["/sbin/qdrouterd", "-c", "/etc/config/qdrouterd.conf" ]
        volumeMounts:
        - mountPath: /var/qdr-certs
          name: qdr-tmp-certs
          readOnly: true
        - mountPath: /etc/config
          name: qdr-proxy-config
          readOnly: true
        resources:
          limits:
            memory: 128Mi

      volumes:
      - name: config
        configMap:
          name: iot-sigfox-adapter-config
      - name: tls
        secret:
          secretName: iot-sigfox-adapter-tls
      - name: qdr-proxy-config
        configMap:
          name: qdr-proxy-configurator
      - name: qdr-tmp-certs
        emptyDir: {}
