apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: iot-custom-device-registry
  name: iot-custom-device-registry-config

data:
  application.yml: |

    hono:
      app:
        maxInstances: 1
        healthCheckBindAddress: 0.0.0.0
        healthCheckPort: 8088
      auth:
        port: 5671
        keyPath: /etc/tls/tls.key
        certPath: /etc/tls/tls.crt
        keyFormat: PEM
        trustStorePath: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        trustStoreFormat: PEM
      registry:
        amqp:
          bindAddress: 0.0.0.0
          keyPath: /etc/tls/tls.key
          certPath: /etc/tls/tls.crt
          keyFormat: PEM
        rest:
          bindAddress: 0.0.0.0
          keyPath: /etc/tls/tls.key
          certPath: /etc/tls/tls.crt
          keyFormat: PEM
        svc:
          filename: /var/lib/hono/device-registry/device-identities.json
          saveToFile: true
      credentials:
        svc:
          credentialsFilename: /var/lib/hono/device-registry/credentials.json
          saveToFile: true
      tenant:
        svc:
          filename: /var/lib/hono/device-registry/tenants.json
          saveToFile: true

  logback-spring.xml: |+
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE xml>
      <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
          <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
          </encoder>
        </appender>
        <root level="INFO">
          <appender-ref ref="STDOUT" />
        </root>
      </configuration>
