apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: iot-custom-device-registry
  name: iot-custom-device-registry-config

data:
  application.yml: |

    hono:

      auth:
        port: 5671
        keyPath: /etc/tls/tls.key
        certPath: /etc/tls/tls.crt
        keyFormat: PEM
        trustStorePath: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        trustStoreFormat: PEM

    enmasse:
      iot:

        app:
          maxInstances: 1

        healthCheck:
          insecurePortBindAddress: 0.0.0.0
          startupTimeout: 90

        registry:

          device:
            credentials:
              ttl: 1m

          amqp:
            bindAddress: 0.0.0.0
            keyPath: /etc/tls/tls.key
            certPath: /etc/tls/tls.crt
            keyFormat: PEM
          rest:
            bindAddress: 0.0.0.0
            keyPath: /etc/tls/tls.key
            certPath: /etc/tls/tls.crt
            keyFormat: PEM

        credentials:
          svc:
            maxBcryptIterations: 10

  logback-spring.xml: |+
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE xml>
      <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
          <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
          </encoder>
        </appender>
        <root level="INFO">
          <appender-ref ref="STDOUT" />
        </root>
      </configuration>
