kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: iot-custom-device-registry
  name: iot-custom-device-registry-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
