kind: BuildConfig
apiVersion: v1
metadata:
  name: qdr-proxy-configurator
  labels:
    enmasse-component: iot
    enmasse-s2i: "true"
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/enmasseproject/enmasse
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: go-toolset-7-custom:latest
      env:
      - name: IMPORT_URL
        value: github.com/enmasseproject/enmasse
      - name: INSTALL_URL
        value: github.com/enmasseproject/enmasse/cmd/qdr-proxy-configurator
  output:
    to:
      kind: ImageStreamTag
      name: qdr-proxy-configurator:latest
