kind: BuildConfig
apiVersion: v1
metadata:
  name: iot-tenant-service
  labels:
    app: iot-registry
    enmasse-component: iot
    enmasse-s2i: "true"
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/enmasseproject/enmasse
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fabric8-s2i-java-custom:java11
      env:
      - name: MAVEN_ARGS_APPEND
        value: -pl io.enmasse:iot-tenant-service --also-make
      - name: ARTIFACT_DIR
        value: iot/iot-tenant-service/target
  output:
    to:
      kind: ImageStreamTag
      name: iot-tenant-service:latest
