kind: BuildConfig
apiVersion: v1
metadata:
  name: fabric8-s2i-java-custom-java11
  labels:
    enmasse-component: iot
    enmasse-s2i: "true"
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/ctron/enmasse-s2i
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fabric8-s2i-java:3.0-java11
      dockerfilePath: containers/fabric8-s2i-java-custom/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: fabric8-s2i-java-custom:java11
