kind: BuildConfig
apiVersion: v1
metadata:
  name: iot-device-registry
  labels:
    app: iot-device-registry
    enmasse-component: iot
    enmasse-s2i: "true"
spec:
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/eclipse/hono
      ref: "0.8.x"
  strategy:
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fabric8-s2i-java-custom:java11
      env:
      - name: MAVEN_ARGS_APPEND
        value: -B -pl org.eclipse.hono:hono-service-device-registry --also-make -Pnetty-tcnative -Pmetrics-prometheus -Pnetty-native-linux-x86_64
        #value: -B -pl org.eclipse.hono:hono-service-device-registry --also-make -Pnetty-tcnative -Pnetty-native-linux-x86_64
      - name: ARTIFACT_DIR
        value: services/device-registry/target
      - name: ARTIFACT_COPY_ARGS
        value: "*-exec.jar"
  output:
    to:
      kind: ImageStreamTag
      name: iot-device-registry:latest
